# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('visibilitymap', ['core'])
    module.source = [
        'model/readVisibilityMap.cc',
        'model/roadElements.cc',
        'model/roadElementPoints.cc',
        'model/initPoints.cc',
        'model/endEdges.cc',
        'model/endPoints.cc',
        'model/losPoint.cc',
        'model/visibilityMap.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'visibilitymap'
    headers.source = [
        'model/readVisibilityMap.h',
        'model/roadElements.h',
        'model/roadElementPoints.h',
        'model/initPoints.h',
        'model/endEdges.h',
        'model/endPoints.h',
        'model/losPoint.h',
        'model/visibilityMap.h'
        ]

    # bld.ns3_python_bindings()

