# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tcpip', ['core'])
    module.source = [
        'model/storage.cc',
		'model/server-socket.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'tcpip'
    headers.source = [
        'model/storage.h',
	'model/server-socket.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

