# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('facilities', ['core', 'internet'])
    module.source = [
        'model/service-list.cc',
        'model/service-management.cc',
        'model/message-management.cc',
        'model/iTETRISns3Facilities.cc',
        'model/addressing-support.cc',
        'model/local-comm-ch-selector.cc',
        'model/MWFacilities.cc',
        'model/mw-comm-ch-selector.cc',
        'model/IPCIUFacilities.cc',
	'helper/mw-facilities-helper.cc',
	'helper/c2c-facilities-helper.cc',
	'helper/service-list-helper.cc',
	'helper/IPCIU-facilities-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'facilities'
    headers.source = [
        'model/service-list.h',
        'model/service-management.h',
        'model/message-management.h',
        'model/iTETRISns3Facilities.h',
        'model/addressing-support.h',
        'model/local-comm-ch-selector.h',
        'model/MWFacilities.h',
        'model/mw-comm-ch-selector.h',
        'model/IPCIUFacilities.h',
	'helper/mw-facilities-helper.h',
	'helper/c2c-facilities-helper.h',
	'helper/service-list-helper.h',
	'helper/IPCIU-facilities-helper.h',
        ]

    # bld.ns3_python_bindings()

