# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('iTETRIS-Application', ['core', 'network'])
    module.source = [
        'model/iTETRIS-Application.cc',
       # 'model/Lte-app.cc', 
    #    'helper/Lte-App-helper.cc', 
        ]

    headers = bld(features='ns3header')
    headers.module = 'iTETRIS-Application'
    headers.source = [
        'model/iTETRIS-Application.h',
     #   'model/Lte-app.h', 
    #    'helper/Lte-App-helper.h', 
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

