# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('messageMgmnt', ['core', 'internet'])
    module.source = [
        'model/CAMmanagement.cc',
	'helper/CAMmanage-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'messageMgmnt'
    headers.source = [
        'model/CAMmanagement.h',
	'helper/CAMmanage-helper.h',
        ]

    # bld.ns3_python_bindings()

