name: linux

on:
  push:            # run on push events
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
  schedule:
    - cron:  '0 0 * * FRI'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning iCS
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Preparing Build System
      run: |
        sudo apt-get update
        sudo apt-get install psmisc vim git cmake autoconf automake libtool libxerces-c-dev libfox-1.6-dev libgl1-mesa-dev libglu1-mesa-dev libgdal-dev libproj-dev libgeographic-dev python3-pip
        sudo pip3 install texttest

    - name: Building
      run: |
        ./build_all.sh

    - name: Running Tests
      run: |
        . setenv.sh
        cd iCS/tests
        texttest -b linux || true
        texttest -b linux -coll

    - name: Deploying Test results to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: github-actions[bot]@users.noreply.github.com
        branch: gh-pages
        build_dir: iCS/tests/ics_report
